Updated target displaying pages with more data
SashaKryzh/ua-validator pull request #11
Opened 2023-03-18 21:55 UTC by denitdao

- fixed search freeze
- updated target search with live data
<img width="856" alt="image" src="https://user-images.githubusercontent.com/49095078/226142301-1c30e5e9-0145-4e6a-9128-d148b4b0dff8.png">
- update target view with all data
<img width="797" alt="image" src="https://user-images.githubusercontent.com/49095078/226142332-020c9b3c-9ba5-4e4f-9116-49bf45c1ec7f.png">
- added new method to get slug

2023-03-18 22:07 UTC, SashaKryzh requested changes
Please review my comments

2023-03-18 22:07 UTC, SashaKryzh commented on src/pages/[name].tsx
> +  target: NonNullable<TargetFindTarget>; // NOTE: we validate target not null in getStaticProps
NonNullable - is it some tRPC or Prisma type? I don't think we should use it here. Can we just use TargetFindTarget?

2023-03-18 22:07 UTC, SashaKryzh commented on src/pages/search.tsx
> +        {/*<div className="px-2">Filters</div>*/}
Let's delete it complelty

2023-03-18 22:07 UTC, SashaKryzh commented on src/server/controller/target.controller.ts
> +  slug = slug.trim();
Maybe also lowercase?

2023-03-18 22:12 UTC, denitdao commented on src/pages/[name].tsx
> +  target: NonNullable<TargetFindTarget>; // NOTE: we validate target not null in getStaticProps
It's native typescript

2023-03-18 22:13 UTC, denitdao commented on src/server/controller/target.controller.ts
> +  slug = slug.trim();
Not needed

2023-03-18 22:13 UTC, SashaKryzh commented on src/pages/[name].tsx
> +  target: NonNullable<TargetFindTarget>; // NOTE: we validate target not null in getStaticProps
Why do you use it if it is nonnullable by default?

2023-03-18 22:17 UTC, denitdao commented on src/pages/[name].tsx
> +  target: NonNullable<TargetFindTarget>; // NOTE: we validate target not null in getStaticProps
It's nullable from prisma actually
We check it in getstaticprops, but page itself still considers it as nullable :(

2023-03-18 22:37 UTC, SashaKryzh commented on src/pages/[name].tsx
> +  target: NonNullable<TargetFindTarget>; // NOTE: we validate target not null in getStaticProps
Page considers its nullable because `TargetFindTarget` is actually a `nullable` type. It's nullable because `prisma.findFirst` may not find anything (null). For this case, I think `NonNullable` is a good use.

2023-03-18 22:38 UTC, SashaKryzh commented on src/pages/[name].tsx
> +  target: NonNullable<TargetFindTarget>; // NOTE: we validate target not null in getStaticProps
Can you please remove the comment in the code because it's not leading to the actual point and may be useless? 🙂

2023-03-19 10:40 UTC, SashaKryzh approved these changes
LGTM

2023-03-19 11:02 UTC, merged