Create target controller and API
SashaKryzh/ua-validator pull request #6
Opened 2023-02-17 22:14 UTC by denitdao

- if slug exists then adding counter
- updated db schema, added indices

```
curl --location --request POST 'http://localhost:3000/api/internal/target' \
--header 'user_name: uav_superuser' \
--header 'Content-Type: application/json' \
--data-raw '[
    {
        "job": "SPORTSMAN",
        "nationality": "RU",
        "viewOnWar": "WITH_ORKY",
        "imageUrl": "/media/brand/%D1%80%D0%BE%D0%BC%D0%B0%D0%BD_%D0%B2%D0%BB%D0%B0%D1%81%D0%BE%D0%B2.jpg",
        "realName": "Роман Власов",
        "nicknames": ["власька"],
        "evidence": {
            "resume": "Пропаганда путінського режиму та підтримка війни проти України.",
            "images": [
                "/media/brand/%D0%B2%D0%BB%D0%B0%D1%81%D0%BE%D0%B2.jpg"
            ]
        },
        "resources": [
            "https://www.instagram.com/vlasovroma90/"
        ]
    }
]'
```

2023-02-17 22:42 UTC, SashaKryzh requested changes

2023-02-17 22:42 UTC, SashaKryzh commented on src/server/schema/target.schema.ts
> +  job: z.enum([
I think you can use `.nativeEnum`

2023-02-17 22:42 UTC, SashaKryzh commented on src/server/controller/target.controller.ts
> +  creatorEmail: string | null;
We need to add a check for a valid email. For example `z.string().email().safeParse()`

2023-02-17 22:42 UTC, SashaKryzh commented on src/server/controller/target.controller.ts
> +                  email: creatorEmail ?? "anonymous",
Let's better store `null` instead of "anonymous"

2023-02-17 22:42 UTC, SashaKryzh commented on prisma/seed.ts
> +  const anonymous = await prisma.creator.upsert({
I think it would be better to not create "anonymous" author, but just pass null or underfined

2023-02-17 22:42 UTC, SashaKryzh commented on src/pages/api/internal/target.ts
> +          errorList.push(target.realName ?? target.nicknames[0] ?? "unknown");
Again, let's make the name `null` and not "unknown"

2023-02-17 22:42 UTC, SashaKryzh commented on src/server/controller/target.controller.ts
> +            email: creatorEmail ?? "anonymous",
let's make the name null and not "anonymous"

2023-02-17 22:42 UTC, SashaKryzh commented on src/server/controller/target.controller.ts
> +  const knownName = input.realName ?? input.nicknames[0] ?? "unknown";
It is not possible that both realName and nickname is undefined. But I think that this check is not implemented yet. We need to figure it out.

2023-02-17 22:42 UTC, SashaKryzh commented on src/pages/api/internal/target.ts
> +          errorList.push(target.realName ?? target.nicknames[0] ?? "unknown");
Ops, it is an errorList. I suggest to not store "unknown" in the db.

2023-02-18 07:41 UTC, denitdao commented on src/server/controller/target.controller.ts
> +  const knownName = input.realName ?? input.nicknames[0] ?? "unknown";
Yes, this is impossible and I even added a constraint to the zod validator. There should be at least one nickname. But typescript doesn't know this.

2023-02-18 09:02 UTC, denitdao commented on src/server/controller/target.controller.ts
> +  creatorEmail: string | null;
We don't do Zod checks in the controller currently, so it's useless in my opinion.
This could be defined when we'll make target creation via UI

2023-02-18 10:36 UTC, merged